import { IsString, IsNotEmpty, IsOptional, IsUUID, IsBoolean } from 'class-validator';

/** DTO for user chat messages sent to Genie Copilot. */
export class CopilotChatDto {
  @IsString()
  @IsNotEmpty()
  message: string;

  @IsOptional()
  @IsUUID()
  sessionId?: string;

  @IsOptional()
  @IsBoolean()
  autoApply?: boolean;
}

/** DTO for direct 1-click alternative swap on place card (Hybrid model). */
export class DirectSwapDto {
  @IsUUID()
  @IsNotEmpty()
  newPlaceId: string;
}

/** DTO for applying a confirmed Copilot proposal. */
export class ApplyProposalDto {
  @IsString()
  @IsNotEmpty()
  toolName: string;

  @IsNotEmpty()
  args: Record<string, unknown>;

  @IsOptional()
  @IsString()
  proposalId?: string;
}

/** Place alternative item returned for card quick pick popover. */
export interface AlternativePlaceItem {
  id: string;
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  ratingAvg: number;
  reviewCount: number;
  priceLevel: string | null;
  imageUrl: string | null;
  categoryName: string;
  distanceKm?: number;
}

/** Result returned from executing a Copilot tool. */
export interface CopilotToolExecutionResult {
  toolName: string;
  success: boolean;
  message: string;
  data?: Record<string, unknown>;
}

/** Proposal generated by Copilot requiring user confirmation before mutation. */
export interface CopilotProposal {
  id: string;
  toolName: string;
  title: string;
  description: string;
  dayNumber?: number;
  fromPlaceId?: string;
  fromPlaceName?: string;
  fromPlaceCoordinates?: {
    latitude: number;
    longitude: number;
  };
  toPlaceId?: string;
  toPlaceName?: string;
  toPlaceRating?: number;
  toPlaceCategory?: string;
  toPlaceAddress?: string;
  toPlaceImageUrl?: string;
  toPlaceCoordinates?: {
    latitude: number;
    longitude: number;
  };
  status?: 'PENDING' | 'APPLIED' | 'REJECTED';
  swapDays?: {
    dayA: number;
    dayB: number;
  };
  args: Record<string, unknown>;
}

/** Final response shape returned to frontend Copilot drawer. */
export interface CopilotChatResponse {
  sessionId: string;
  reply: string;
  modified: boolean;
  action?: {
    type: 'CREATE_NEW_TRIP';
    destination: string;
  };
  appliedTool?: {
    name: string;
    args: Record<string, unknown>;
    resultMessage: string;
  };
  proposal?: CopilotProposal;
  itinerary?: unknown;
}

/** Historical message record returned to frontend. */
export interface CopilotMessageHistoryItem {
  id: string;
  sender: 'user' | 'agent';
  content: string;
  createdAt: string;
  toolCalls?: unknown;
  proposal?: CopilotProposal;
}

// =============================================================================
// GEMINI TOOL FUNCTION DECLARATIONS & CONSTANTS (Typed and Constant)
// =============================================================================

export const COPILOT_CONSTANTS = {
  SLIDING_WINDOW_SIZE: 8,
  SUMMARIZATION_THRESHOLD: 12,
  SUMMARY_BATCH_SIZE: 8,
  SUMMARY_MAX_TOKENS: 250,
} as const;

export const COPILOT_SUMMARY_QUEUE = 'copilot-summary';
export const COPILOT_SUMMARY_JOB = 'summarize-session';

export const COPILOT_TOOL_NAMES = {
  SWAP_ACTIVITY: 'swap_activity',
  ADD_ACTIVITY: 'add_activity',
  REMOVE_ACTIVITY: 'remove_activity',
  MOVE_ACTIVITY: 'move_activity',
  SWAP_DAYS: 'swap_days',
  CHANGE_DESTINATION: 'change_destination',
} as const;

export type CopilotToolName = (typeof COPILOT_TOOL_NAMES)[keyof typeof COPILOT_TOOL_NAMES];

export const COPILOT_FUNCTION_DECLARATIONS = [
  {
    name: COPILOT_TOOL_NAMES.CHANGE_DESTINATION,
    description:
      'Gọi công cụ này khi người dùng muốn đổi điểm đến của chuyến đi sang một tỉnh/thành phố hoặc địa phương khác (ví dụ: muốn đổi từ Đà Nẵng sang Phú Quốc, Nha Trang, Đà Lạt, Hà Nội, Sa Pa...).',
    parameters: {
      type: 'OBJECT',
      properties: {
        newDestination: {
          type: 'STRING',
          description: 'Tên tỉnh/thành phố hoặc điểm đến mới mà người dùng muốn đi tới.',
        },
      },
      required: ['newDestination'],
    },
  },
  {
    name: COPILOT_TOOL_NAMES.SWAP_ACTIVITY,
    description:
      'Đổi một địa điểm/hoạt động trong lịch trình sang một địa điểm khác theo yêu cầu của người dùng (ví dụ đổi quán ăn trưa sang quán hải sản, đổi quán cafe, đổi điểm tham quan).',
    parameters: {
      type: 'OBJECT',
      properties: {
        dayNumber: {
          type: 'INTEGER',
          description:
            'Số thứ tự ngày của địa điểm trong lịch trình (ví dụ: 1, 2, 3). Tra cứu đúng ngày của địa điểm trong LỊCH TRÌNH HIỆN TẠI.',
        },
        currentPlaceName: {
          type: 'STRING',
          description:
            'Tên chính xác của địa điểm hiện tại trong lịch trình mà người dùng muốn thay thế (ví dụ: "Mì Quảng Bà Mua (Trần Bình Trọng)"). QUAN TRỌNG: Nếu người dùng đang chọn đổi cho địa điểm đã bàn ở câu trước hoặc chỉ định rõ tên quán, BẮT BUỘC phải truyền tên quán đó vào đây!',
        },
        mealOrActivityType: {
          type: 'STRING',
          description: 'Loại hoạt động hoặc bữa ăn: sáng, trưa, tối, cafe, tham quan, giải trí.',
        },
        query: {
          type: 'STRING',
          description:
            'Tên hoặc thể loại địa điểm mới người dùng muốn đổi sang (ví dụ: "Hải Sản Năm Đảnh (Trần Quang Khải)", "quán hải sản").',
        },
      },
      required: ['query'],
    },
  },
  {
    name: COPILOT_TOOL_NAMES.ADD_ACTIVITY,
    description:
      'Thêm một địa điểm hoặc hoạt động mới vào một ngày trong lịch trình (ví dụ: thêm quán cafe sáng, thêm quán bar/pub tối, thêm điểm tham quan).',
    parameters: {
      type: 'OBJECT',
      properties: {
        dayNumber: {
          type: 'INTEGER',
          description: 'Số thứ tự ngày muốn thêm địa điểm (ví dụ: 1, 2, 3).',
        },
        timeSlot: {
          type: 'STRING',
          description: 'Khung giờ hoặc buổi muốn chèn: "morning" (sáng), "lunch" (trưa), "afternoon" (chiều), "dinner" (tối), "night" (đêm).',
        },
        query: {
          type: 'STRING',
          description: 'Tên hoặc thể loại địa điểm muốn thêm (ví dụ: "quán bar chill nhạc acoustic", "tiệm bánh mì đặc sản").',
        },
      },
      required: ['dayNumber', 'query'],
    },
  },
  {
    name: COPILOT_TOOL_NAMES.REMOVE_ACTIVITY,
    description:
      'Xóa một địa điểm/hoạt động ra khỏi lịch trình (ví dụ: xóa bớt 1 điểm vì mệt, bỏ quán cafe chiều, về sớm).',
    parameters: {
      type: 'OBJECT',
      properties: {
        dayNumber: {
          type: 'INTEGER',
          description: 'Số thứ tự ngày chứa hoạt động muốn xóa.',
        },
        placeName: {
          type: 'STRING',
          description: 'Tên hoặc từ khóa nhận diện địa điểm muốn xóa.',
        },
      },
      required: ['dayNumber', 'placeName'],
    },
  },
  {
    name: COPILOT_TOOL_NAMES.MOVE_ACTIVITY,
    description:
      'Di chuyển một địa điểm từ ngày này sang ngày khác trong lịch trình (ví dụ: dời Chùa Linh Ứng từ chiều ngày 1 sang sáng ngày 2).',
    parameters: {
      type: 'OBJECT',
      properties: {
        placeName: {
          type: 'STRING',
          description: 'Tên địa điểm muốn di chuyển.',
        },
        fromDay: {
          type: 'INTEGER',
          description: 'Ngày hiện tại chứa địa điểm.',
        },
        toDay: {
          type: 'INTEGER',
          description: 'Ngày đích muốn chuyển địa điểm tới.',
        },
        targetTimeSlot: {
          type: 'STRING',
          description: 'Khung giờ ở ngày đích: "morning", "afternoon", "evening". Mặc định "afternoon".',
        },
      },
      required: ['placeName', 'fromDay', 'toDay'],
    },
  },
  {
    name: COPILOT_TOOL_NAMES.SWAP_DAYS,
    description:
      'Hoán đổi toàn bộ lịch trình giữa 2 ngày cho nhau (ví dụ: đổi lịch ngày 1 với ngày 2 vì ngày 1 trời mưa).',
    parameters: {
      type: 'OBJECT',
      properties: {
        dayA: {
          type: 'INTEGER',
          description: 'Số thứ tự ngày thứ nhất (ví dụ: 1).',
        },
        dayB: {
          type: 'INTEGER',
          description: 'Số thứ tự ngày thứ hai (ví dụ: 2).',
        },
      },
      required: ['dayA', 'dayB'],
    },
  },
];
