export const INJECT_TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  PLACE_REPOSITORY: 'PLACE_REPOSITORY',
  ITINERARY_REPOSITORY: 'ITINERARY_REPOSITORY',
  AI_SERVICE: 'AI_SERVICE',
  CRAWLER_SERVICE: 'CRAWLER_SERVICE',
  ROUTING_SERVICE: 'ROUTING_SERVICE',
} as const;
