export const INJECT_TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  PLACE_REPOSITORY: 'PLACE_REPOSITORY',
  ITINERARY_REPOSITORY: 'ITINERARY_REPOSITORY',
  CRAWLER_REPOSITORY: 'CRAWLER_REPOSITORY',
  OSM_PROVIDER: 'OSM_PROVIDER',
  FOURSQUARE_PROVIDER: 'FOURSQUARE_PROVIDER',
  WIKIMEDIA_PROVIDER: 'WIKIMEDIA_PROVIDER',
  ENRICHMENT_PROVIDERS: 'ENRICHMENT_PROVIDERS',
  OSM_INGESTION_SERVICE: 'OSM_INGESTION_SERVICE',
  AI_SERVICE: 'AI_SERVICE',
  CRAWLER_SERVICE: 'CRAWLER_SERVICE',
  ROUTING_SERVICE: 'ROUTING_SERVICE',
} as const;
